[package]
name = "furiosa-client"
version = "0.3.1"
authors = ["Furiosa.AI"]
edition = "2018"

[lib]
path = "src/lib.rs"

[features]
default = []
blocking = []

[dependencies]
dirs = "3"
dotenv = "0.15"
log = "0.4"
lazy_static = "1.4.0"
thiserror = "1"
reqwest = { version = "0.10.7", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
env_logger = "0.7"
