num_pe: 2
num_registers: 32
size_dram: 17179869184
size_dram_bulk: 32
size_actual_sram_slice: 262144
size_sram_slice_address_space: 1048576
size_instruction_memory: 262144
num_operands: 4
operand_queue_depth: 12
num_tasks: 7
scalar_alignment: 4
io_alignment: 32
hop_cycles: 2
ctrl_delay: 2
shift_register_width: 48
gat_data_width: 2
gat_hop_cycles: 2
num_slices: 64
mac_width: 32
mac_height: 4
num_table_ports: 2
sram_access_width: 8
register_file_size: 8192
accumulator_size: 4
ve_register_file_size: 128
ve_max_access_width: 2
warmup_base: 20
fetch_network_width: 16
sfr_io_width: 4
te_io_width: 8
completion_tag_width: 5
